### ISSUE TITLE
DockerCompose WARD_FOG ENV Variable Not Working

### ISSUE THREAD

**Issue by Techeryy** [AntonyLeons/Ward#115]
Switching the WARD_FOG environment variable to on or off doesn't change anything - the fog is always there, my docker compose file for reference:
```
version: '3.3'

networks:
  backend:
    external: true

services:
  run:
    container_name: Ward
    image: antonyleons/ward
    restart: always
    environment:
      - WARD_PORT=4000
      - WARD_THEME=dark
      - WARD_FOG=false
      - WARD_NAME=Something
      - WARD_BACKGROUND=#3c3c3c
    privileged: true
    networks:
      - backend
```
